"""Контент игры: категории слов (классика / двойной агент) и
локации с ролями (режим "роли", аналог оригинального Spyfall).

Список легко расширять — просто добавляй новые словари в
CLASSIC_CATEGORIES / ROLE_LOCATIONS.
"""

CLASSIC_CATEGORIES = {
    "dota2": {
        "title": "🎮 Dota 2 (герои)",
        "words": [
            "Anti-Mage", "Axe", "Bane", "Bloodseeker", "Crystal Maiden",
            "Drow Ranger", "Earthshaker", "Juggernaut", "Mirana", "Morphling",
            "Shadow Fiend", "Phantom Lancer", "Puck", "Pudge", "Razor",
            "Sand King", "Storm Spirit", "Sven", "Tiny", "Vengeful Spirit",
            "Windranger", "Zeus", "Kunkka", "Lina", "Lion",
            "Shadow Shaman", "Slardar", "Tidehunter", "Witch Doctor", "Lich",
            "Riki", "Enigma", "Tinker", "Sniper", "Necrophos",
            "Warlock", "Beastmaster", "Queen of Pain", "Venomancer", "Faceless Void",
            "Wraith King", "Death Prophet", "Phantom Assassin", "Pugna", "Templar Assassin",
            "Viper", "Luna", "Dragon Knight", "Dazzle", "Clockwerk",
            "Leshrac", "Nature's Prophet", "Lifestealer", "Dark Seer", "Clinkz",
            "Omniknight", "Enchantress", "Huskar", "Night Stalker", "Broodmother",
            "Bounty Hunter", "Weaver", "Jakiro", "Batrider", "Chen",
            "Spectre", "Ancient Apparition", "Doom", "Ursa", "Spirit Breaker",
            "Gyrocopter", "Alchemist", "Invoker", "Silencer", "Outworld Destroyer",
            "Lycan", "Brewmaster", "Shadow Demon", "Ember Spirit", "Earth Spirit",
            "Underlord", "Terrorblade", "Phoenix", "Oracle", "Winter Wyvern",
            "Arc Warden", "Monkey King", "Dark Willow", "Pangolier", "Grimstroke",
            "Hoodwink", "Void Spirit", "Snapfire", "Mars", "Dawnbreaker",
            "Marci", "Primal Beast", "Muerta", "Ringmaster", "Kez",
            "Legion Commander", "Skywrath Mage", "Elder Titan", "Abaddon", "Centaur Warrunner",
            "Chaos Knight", "Magnus", "Timbersaw", "Treant Protector", "Keeper of the Light",
            "Io", "Visage", "Techies", "Meepo", "Troll Warlord",
            "Undying", "Bristleback", "Naga Siren", "Rubick", "Disruptor",
        ],
    },
    "lol": {
        "title": "🎮 League of Legends (чемпионы)",
        "words": [
            "Aatrox", "Ahri", "Akali", "Akshan", "Alistar",
            "Ambessa", "Amumu", "Anivia", "Annie", "Aphelios",
            "Ashe", "Aurelion Sol", "Aurora", "Azir", "Bard",
            "Bel'Veth", "Blitzcrank", "Brand", "Braum", "Briar",
            "Caitlyn", "Camille", "Cassiopeia", "Cho'Gath", "Corki",
            "Darius", "Diana", "Dr. Mundo", "Draven", "Ekko",
            "Elise", "Evelynn", "Ezreal", "Fiddlesticks", "Fiora",
            "Fizz", "Galio", "Gangplank", "Garen", "Gnar",
            "Gragas", "Graves", "Gwen", "Hecarim", "Heimerdinger",
            "Hwei", "Illaoi", "Irelia", "Ivern", "Janna",
            "Jarvan IV", "Jax", "Jayce", "Jhin", "Jinx",
            "K'Sante", "Kai'Sa", "Kalista", "Karma", "Karthus",
            "Kassadin", "Katarina", "Kayle", "Kayn", "Kennen",
            "Kha'Zix", "Kindred", "Kled", "Kog'Maw", "LeBlanc",
            "Lee Sin", "Leona", "Lillia", "Lissandra", "Lucian",
            "Lulu", "Lux", "Malphite", "Malzahar", "Maokai",
            "Master Yi", "Milio", "Miss Fortune", "Mordekaiser", "Morgana",
            "Naafiri", "Nami", "Nasus", "Nautilus", "Neeko",
            "Nidalee", "Nilah", "Nocturne", "Nunu & Willump", "Olaf",
            "Orianna", "Ornn", "Pantheon", "Poppy", "Pyke",
            "Qiyana", "Quinn", "Rakan", "Rammus", "Rek'Sai",
            "Rell", "Renata Glasc", "Renekton", "Rengar", "Riven",
            "Rumble", "Ryze", "Samira", "Sejuani", "Senna",
            "Seraphine", "Sett", "Shaco", "Shen", "Shyvana",
            "Singed", "Sion", "Sivir", "Skarner", "Smolder",
            "Sona", "Soraka", "Swain", "Sylas", "Syndra",
            "Tahm Kench", "Taliyah", "Talon", "Taric", "Teemo",
            "Thresh", "Tristana", "Trundle", "Tryndamere", "Twisted Fate",
            "Twitch", "Udyr", "Urgot", "Varus", "Vayne",
            "Veigar", "Vel'Koz", "Vex", "Vi", "Viego",
            "Viktor", "Vladimir", "Volibear", "Warwick", "Wukong",
            "Xayah", "Xerath", "Xin Zhao", "Yasuo", "Yone",
            "Yorick", "Yunara", "Yuumi", "Zac", "Zed",
            "Zeri", "Ziggs", "Zilean", "Zoe", "Zyra",
        ],
    },
    "movies": {
        "title": "🎬 Фильмы",
        "words": [
            "Титаник", "Матрица", "Гарри Поттер", "Интерстеллар", "Джокер",
            "Крёстный отец", "Бойцовский клуб", "Терминатор", "Аватар",
            "Ла-Ла Ленд", "Начало", "Зелёная миля", "Пираты Карибского моря",
            "Шрек", "Гладиатор", "Список Шиндлера", "Форрест Гамп",
            "Криминальное чтиво", "Побег из Шоушенка", "Властелин колец",
            "Звёздные войны", "Мстители", "Тёмный рыцарь", "Волк с Уолл-стрит",
            "Достать ножи", "Основатель", "Дюна", "Однажды в Голливуде",
            "Остров проклятых", "Семь", "Молчание ягнят", "Изгой",
            "Игра в имитацию", "Умница Уилл Хантинг", "Красотка", "Титан",
            "Малышка на миллион", "Реквием по мечте", "Помни", "Куда приводят мечты",
            "Зелёная книга", "Паразиты", "Оппенгеймер", "Барби",
            "Джентльмены", "Игра Престолов", "Ходячие мертвецы", "Один дома",
            "Назад в будущее", "Индиана Джонс", "Человек-паук", "Бэтмен",
            "Веном", "Дэдпул", "Стражи Галактики", "Тор", "Гарри Поттер и философский камень",
            "Хроники Нарнии", "Сумерки", "Голодные игры", "Дивергент",
            "Малефисента", "Красавица и чудовище", "Русалочка", "Аладдин",
        ],
    },
    "actors": {
        "title": "🎭 Актёры",
        "words": [
            "Том Круз", "Леонардо Ди Каприо", "Брэд Питт", "Джонни Депп",
            "Скарлетт Йоханссон", "Уилл Смит", "Дуэйн Джонсон", "Райан Гослинг",
            "Эмма Стоун", "Кристиан Бейл", "Марго Робби", "Роберт Дауни мл.",
            "Дженнифер Лоуренс", "Хью Джекман", "Анджелина Джоли",
            "Киану Ривз", "Мэттью Макконахи", "Морган Фриман", "Дензел Вашингтон",
            "Аль Пачино", "Роберт Де Ниро", "Джек Николсон", "Энтони Хопкинс",
            "Хоакин Феникс", "Том Хэнкс", "Мэтт Дэймон", "Эдвард Нортон",
            "Кевин Спейси", "Сэмюэл Л. Джексон", "Джейсон Стэйтем", "Крис Хемсворт",
            "Крис Эванс", "Марк Руффало", "Бенедикт Камбербэтч", "Идрис Эльба",
            "Джаред Лето", "Райан Рейнольдс", "Джейк Джилленхол", "Тимоти Шаламе",
            "Николь Кидман", "Шарлиз Терон", "Натали Портман", "Кейт Уинслет",
            "Меган Фокс", "Эмма Уотсон", "Сандра Буллок", "Джулия Робертс",
            "Пенелопа Крус", "Кира Найтли", "Зендея", "Галь Гадот",
            "Милла Йовович", "Ума Турман", "Шарлиз Терон", "Мила Кунис",
        ],
    },
    "animals": {
        "title": "🐼 Животные",
        "words": [
            "Панда", "Слон", "Кот", "Собака", "Дельфин", "Орёл", "Змея",
            "Тигр", "Жираф", "Кенгуру", "Пингвин", "Крокодил", "Лиса",
            "Медведь", "Осьминог", "Лев", "Волк", "Заяц", "Белка",
            "Ёж", "Барсук", "Енот", "Бобёр", "Олень", "Лось",
            "Носорог", "Бегемот", "Зебра", "Гепард", "Леопард",
            "Ягуар", "Рысь", "Горилла", "Шимпанзе", "Орангутан",
            "Коала", "Ленивец", "Броненосец", "Муравьед", "Скунс",
            "Выдра", "Тюлень", "Морж", "Кит", "Акула",
            "Морская черепаха", "Медуза", "Краб", "Омар", "Скат",
            "Сова", "Ворон", "Попугай", "Фламинго", "Пеликан",
            "Страус", "Павлин", "Лебедь", "Аист", "Ястреб",
            "Хамелеон", "Игуана", "Варан", "Питон", "Кобра",
            "Летучая мышь", "Крыса", "Хомяк", "Морская свинка", "Кролик",
        ],
    },
}

# Режим "роли": локация + список ролей.
# Важно: ролей в списке должно быть не меньше, чем максимум
# играющих-нешпионов, иначе часть игроков получит роль "Гость".
ROLE_LOCATIONS = {
    "zoo": {
        "title": "🦁 Зоопарк",
        "roles": [
            "Ветеринар", "Кассир", "Директор", "Посетитель", "Уборщик",
            "Экскурсовод", "Кормщик животных", "Охранник", "Фотограф",
            "Продавец шариков", "Дрессировщик", "Смотритель за птицами",
        ],
    },
    "hospital": {
        "title": "🏥 Больница",
        "roles": [
            "Хирург", "Медсестра", "Пациент", "Регистратор", "Санитар",
            "Анестезиолог", "Практикант", "Родственник пациента", "Охранник",
            "Главврач", "Лаборант", "Психолог",
        ],
    },
    "restaurant": {
        "title": "🍽 Ресторан",
        "roles": [
            "Шеф-повар", "Официант", "Администратор", "Посетитель", "Сомелье",
            "Посудомойщик", "Музыкант", "Бариста", "Хостес", "Кондитер",
            "Курьер", "Владелец",
        ],
    },
    "plane": {
        "title": "✈️ Самолёт",
        "roles": [
            "Пилот", "Стюардесса", "Пассажир", "Механик", "Диспетчер",
            "Бизнес-пассажир", "Пассажир с ребёнком", "Смотрящий за порядком",
            "Бортпроводник", "VIP-гость", "Техник", "Штурман",
        ],
    },
    "school": {
        "title": "🏫 Школа",
        "roles": [
            "Учитель", "Директор", "Ученик", "Завуч", "Охранник",
            "Уборщица", "Библиотекарь", "Школьный психолог", "Повар в столовой",
            "Родитель", "Физрук", "Вахтёр",
        ],
    },
}
